"""add new model for achievements

Revision ID: 1a3ede71191f
Revises: 79becb1cf83f
Create Date: 2026-07-03 15:28:22.896701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a3ede71191f'
down_revision: Union[str, Sequence[str], None] = '79becb1cf83f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steam_tracked_gamses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.String(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=False),
    sa.Column('game_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['steam_id'], ['steam_users.steam_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('steam_id', 'app_id')
    )
    op.create_index(op.f('ix_steam_tracked_gamses_id'), 'steam_tracked_gamses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steam_tracked_gamses_id'), table_name='steam_tracked_gamses')
    op.drop_table('steam_tracked_gamses')
    # ### end Alembic commands ###
