"""add fieds for muscles

Revision ID: 6ae3d90125a9
Revises: a893c86498a9
Create Date: 2026-06-30 11:17:46.503116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ae3d90125a9'
down_revision: Union[str, Sequence[str], None] = 'a893c86498a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('muscle_group', sa.Enum('Ноги', 'ГРУДЬ', 'БИЦЕПС', 'ТРИЦЕПС', 'СПИНА', 'ПЛЕЧИ', 'ПРЕСС', name='musclegroup', native_enum=False), nullable=False))
    op.add_column('exercises', sa.Column('exercise_type', sa.Enum('КАРДИО', 'СИЛОВОЕ', 'РАСТЯЖКА', name='exercisetype', native_enum=False), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'exercise_type')
    op.drop_column('exercises', 'muscle_group')
    # ### end Alembic commands ###
