"""upd models for trainings and exercises

Revision ID: 7860dd507498
Revises: a1b2c3d4e5f6
Create Date: 2026-06-24 11:23:08.461282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7860dd507498'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('training_exercises', sa.Column('quantity', sa.Integer(), nullable=True))
    op.add_column('training_exercises', sa.Column('weight', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('training_exercises', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('training_exercises_training_id_exercise_id_key'), 'training_exercises', type_='unique')
    op.create_unique_constraint(None, 'training_exercises', ['training_id', 'exercise_id', 'user_id'])
    op.create_foreign_key(None, 'training_exercises', 'users', ['user_id'], ['id'])
    op.drop_column('trainings', 'quantity')
    op.drop_column('trainings', 'weight')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainings', sa.Column('weight', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.add_column('trainings', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'training_exercises', type_='foreignkey')
    op.drop_constraint(None, 'training_exercises', type_='unique')
    op.create_unique_constraint(op.f('training_exercises_training_id_exercise_id_key'), 'training_exercises', ['training_id', 'exercise_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('training_exercises', 'user_id')
    op.drop_column('training_exercises', 'weight')
    op.drop_column('training_exercises', 'quantity')
    # ### end Alembic commands ###
