"""add new model for steam users

Revision ID: 79becb1cf83f
Revises: 8162aa223197
Create Date: 2026-06-30 15:01:19.429608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79becb1cf83f'
down_revision: Union[str, Sequence[str], None] = '8162aa223197'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('steam_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('steam_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_steam_users_id'), 'steam_users', ['id'], unique=False)
    op.create_index(op.f('ix_steam_users_steam_id'), 'steam_users', ['steam_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_steam_users_steam_id'), table_name='steam_users')
    op.drop_index(op.f('ix_steam_users_id'), table_name='steam_users')
    op.drop_table('steam_users')
    # ### end Alembic commands ###
