"""upd models for tainigs and exercises

Revision ID: 88d4dd86ba77
Revises: eb3ecfbb12cc
Create Date: 2026-06-23 10:58:51.567832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88d4dd86ba77'
down_revision: Union[str, Sequence[str], None] = 'eb3ecfbb12cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.drop_constraint('exercises_pkey', 'exercises', type_='primary')
    op.create_primary_key('exercises_pkey', 'exercises', ['id'])
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['training_id'], ['trainings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_id', 'exercise_id')
    )
    op.create_index(op.f('ix_training_exercises_id'), 'training_exercises', ['id'], unique=False)
    op.alter_column('trainings', 'weight',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trainings', 'weight',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=3, scale=2),
               existing_nullable=False)
    op.drop_index(op.f('ix_training_exercises_id'), table_name='training_exercises')
    op.drop_table('training_exercises')
    op.drop_constraint('exercises_pkey', 'exercises', type_='primary')
    op.create_primary_key('exercises_pkey', 'exercises', ['id', 'name'])
    # ### end Alembic commands ###
