"""add accounts type

Revision ID: 93fff30bd4c4
Revises: 3a266feb1729
Create Date: 2026-07-13 10:57:15.454728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93fff30bd4c4'
down_revision: Union[str, Sequence[str], None] = '3a266feb1729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_type', sa.Enum('Обычный', 'Накопительный', 'Инвестиционный', name='accounttype', native_enum=False), server_default='Обычный', nullable=False))
    op.add_column('accounts', sa.Column('goal_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'goal_amount')
    op.drop_column('accounts', 'account_type')
    # ### end Alembic commands ###
