"""init

Revision ID: a80f19647e0b
Revises: 
Create Date: 2026-03-03 18:06:32.265873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a80f19647e0b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('category_id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('account_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'account_id')
    op.drop_column('transactions', 'category_id')
    # ### end Alembic commands ###
