"""add fied for shoing category in analytics page

Revision ID: a893c86498a9
Revises: 7860dd507498
Create Date: 2026-06-30 10:22:52.199180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a893c86498a9'
down_revision: Union[str, Sequence[str], None] = '7860dd507498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default='true' заполняет существующие строки при добавлении колонки
    op.add_column('categories', sa.Column('show_analytics', sa.Boolean(), nullable=False, server_default=sa.text('true')))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'show_analytics')
    # ### end Alembic commands ###
